packages:
  - "barazo-lexicons"
  - "barazo-api"
  - "barazo-web"
  - "barazo-plugins"

catalog:
  zod: "^4.3.6"
  vitest: "^4.0.18"
  typescript: "^5.9.3"
  typescript-eslint: "^8.56.0"
  eslint: "^9.39.2"
  "@types/node": "^25.2.3"
  "@commitlint/cli": "^20.4.1"
  "@commitlint/config-conventional": "^20.4.1"
  "@vitest/coverage-v8": "^4.0.18"
  husky: "^9.1.7"
  lint-staged: "^16.2.7"
  multiformats: "^13.4.2"
  prettier: "^3.8.1"
